In [1]:
from sklearn.preprocessing import  OneHotEncoder
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, AdaBoostClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.svm import SVC
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from xgboost import XGBClassifier



In [2]:
df= pd.read_csv('diabetes_data.csv')


In [3]:
for col in df.columns:
    print(f"{col}: {df[col].nunique()}")

PatientID: 1879
Age: 71
Gender: 2
Ethnicity: 4
SocioeconomicStatus: 3
EducationLevel: 4
BMI: 1879
Smoking: 2
AlcoholConsumption: 1879
PhysicalActivity: 1879
DietQuality: 1879
SleepQuality: 1879
FamilyHistoryDiabetes: 2
GestationalDiabetes: 2
PolycysticOvarySyndrome: 2
PreviousPreDiabetes: 2
Hypertension: 2
SystolicBP: 90
DiastolicBP: 60
FastingBloodSugar: 1879
HbA1c: 1879
SerumCreatinine: 1879
BUNLevels: 1879
CholesterolTotal: 1879
CholesterolLDL: 1879
CholesterolHDL: 1879
CholesterolTriglycerides: 1879
AntihypertensiveMedications: 2
Statins: 2
AntidiabeticMedications: 2
FrequentUrination: 2
ExcessiveThirst: 2
UnexplainedWeightLoss: 2
FatigueLevels: 1879
BlurredVision: 2
SlowHealingSores: 2
TinglingHandsFeet: 2
QualityOfLifeScore: 1879
HeavyMetalsExposure: 2
OccupationalExposureChemicals: 2
WaterQuality: 2
MedicalCheckupsFrequency: 1879
MedicationAdherence: 1879
HealthLiteracy: 1879
Diagnosis: 2
DoctorInCharge: 1


In [4]:
df = df.drop(['PatientID', 'DoctorInCharge'], axis=1)
df

Age  Gender  Ethnicity  SocioeconomicStatus  EducationLevel        BMI  \
0      44       0          1                    2               1  32.985284   
1      51       1          0                    1               2  39.916764   
2      89       1          0                    1               3  19.782251   
3      21       1          1                    1               2  32.376881   
4      27       1          0                    1               3  16.808600   
...   ...     ...        ...                  ...             ...        ...   
1874   37       0          0                    2               2  20.811137   
1875   80       1          0                    2               2  27.694312   
1876   38       1          0                    0               2  35.640824   
1877   43       0          1                    2               0  32.423016   
1878   85       1          0                    2               2  33.145119   

      Smoking  AlcoholConsumption  PhysicalActivity  DietQuality  ...  \
0           1            4.499365          2.443385     4.898831  ...   
1           0            1.578919          8.301264     8.941093  ...   
2           0            1.177301          6.103395     7.722543  ...   
3           1            1.714621          8.645465     4.804044  ...   
4           0           15.462549          4.629383     2.532756  ...   
...       ...                 ...               ...          ...  ...   
1874        0           10.946207          3.217636     8.338196  ...   
1875        0           16.067905          7.107335     3.034771  ...   
1876        0            4.865124          9.881212     2.657002  ...   
1877        0            6.362936          4.750079     8.736024  ...   
1878        0           13.854861          5.434137     5.127496  ...   

      SlowHealingSores  TinglingHandsFeet  QualityOfLifeScore  \
0                    0                  1           73.765109   
1                    0                  0           91.445753   
2                    0                  0           54.485744   
3                    0                  0           77.866758   
4                    0                  0           37.731808   
...                ...                ...                 ...   
1874                 0                  1           88.122729   
1875                 1                  0           77.128599   
1876                 0                  0           13.148221   
1877                 0                  0           54.370980   
1878                 0                  1           43.720860   

      HeavyMetalsExposure  OccupationalExposureChemicals  WaterQuality  \
0                       0                              0             0   
1                       0                              0             1   
2                       0                              0             0   
3                       0                              0             1   
4                       0                              0             0   
...                   ...                            ...           ...   
1874                    0                              0             1   
1875                    0                              0             1   
1876                    0                              0             0   
1877                    0                              0             0   
1878                    0                              0             1   

      MedicalCheckupsFrequency  MedicationAdherence  HealthLiteracy  Diagnosis  
0                     1.782724             4.486980        7.211349          1  
1                     3.381070             5.961705        5.024612          1  
2                     2.701019             8.950821        7.034944          0  
3                     1.409056             3.124769        4.717774          0  
4                     1.218452             6.977741        7.887940          0  
...         

In [5]:
numerical_features = [ 
    'Age', 
    'BMI', 
    'AlcoholConsumption', 
    'PhysicalActivity', 
    'DietQuality', 
    'SleepQuality', 
    'SystolicBP', 
    'DiastolicBP', 
    'FastingBloodSugar', 
    'HbA1c', 
    'SerumCreatinine', 
    'BUNLevels', 
    'CholesterolTotal', 
    'CholesterolLDL', 
    'CholesterolHDL', 
    'CholesterolTriglycerides', 
    'FatigueLevels', 
    'QualityOfLifeScore', 
    'MedicalCheckupsFrequency', 
    'MedicationAdherence', 
    'HealthLiteracy'
]

categorical_features = [
    'Gender', 
    'Ethnicity', 
    'SocioeconomicStatus', 
    'EducationLevel', 
    'Smoking', 
    'FamilyHistoryDiabetes', 
    'GestationalDiabetes', 
    'PolycysticOvarySyndrome', 
    'PreviousPreDiabetes', 
    'Hypertension', 
    'AntihypertensiveMedications', 
    'Statins', 
    'AntidiabeticMedications', 
    'FrequentUrination', 
    'ExcessiveThirst', 
    'UnexplainedWeightLoss', 
    'BlurredVision', 
    'SlowHealingSores', 
    'TinglingHandsFeet', 
    'HeavyMetalsExposure', 
    'OccupationalExposureChemicals', 
    'WaterQuality', 
    'Diagnosis'
]

In [6]:
# Compute the correlation matrix
corr = df.corr()

corr_table = pd.DataFrame(corr)

corr_table

target_feature = 'Diagnosis'
corr_table


Age    Gender  Ethnicity  \
Age                            1.000000 -0.000856  -0.049707   
Gender                        -0.000856  1.000000  -0.010411   
Ethnicity                     -0.049707 -0.010411   1.000000   
SocioeconomicStatus           -0.007782 -0.000957  -0.017719   
EducationLevel                 0.005520  0.014952   0.012042   
BMI                            0.006928  0.020455  -0.005440   
Smoking                        0.010858  0.000275  -0.022346   
AlcoholConsumption            -0.017781 -0.038466  -0.042909   
PhysicalActivity               0.017811  0.006692   0.002575   
DietQuality                    0.036613  0.002963  -0.000708   
SleepQuality                  -0.025745 -0.005774   0.002341   
FamilyHistoryDiabetes          0.018797  0.014000  -0.036448   
GestationalDiabetes            0.040820  0.024323   0.002852   
PolycysticOvarySyndrome       -0.001836  0.005413   0.025868   
PreviousPreDiabetes           -0.008952  0.000338  -0.011837   
Hypertension                  -0.032298 -0.010043   0.051279   
SystolicBP                    -0.003944 -0.035896  -0.014026   
DiastolicBP                    0.022890 -0.015992   0.035743   
FastingBloodSugar             -0.022774 -0.017246   0.020774   
HbA1c                          0.016533  0.042190  -0.038147   
SerumCreatinine               -0.008761 -0.020745  -0.013801   
BUNLevels                     -0.011914  0.004462   0.024926   
CholesterolTotal               0.036122 -0.004767   0.003048   
CholesterolLDL                 0.005428  0.038656   0.012341   
CholesterolHDL                 0.052419  0.015712  -0.000036   
CholesterolTriglycerides      -0.026417  0.007907   0.029322   
AntihypertensiveMedications   -0.024877 -0.004204   0.001325   
Statins                        0.013764 -0.015205  -0.045146   
AntidiabeticMedications        0.000084  0.002473  -0.011613   
FrequentUrination             -0.036307 -0.055795  -0.018348   
ExcessiveThirst               -0.011939  0.035167   0.015025   
UnexplainedWeightLoss         -0.041848  0.001964  -0.005983   
FatigueLevels                  0.018845  0.017494   0.002890   
BlurredVision                 -0.005455 -0.022708  -0.026439   
SlowHealingSores               0.008862  0.006712  -0.019843   
TinglingHandsFeet              0.011553  0.000386  -0.003145   
QualityOfLifeScore            -0.001543 -0.033461   0.018857   
HeavyMetalsExposure            0.007326 -0.042018  -0.025280   
OccupationalExposureChemicals  0.019327 -0.040498  -0.034420   
WaterQuality                  -0.039539  0.003230  -0.016378   
MedicalCheckupsFrequency      -0.003905  0.049901  -0.025778   
MedicationAdherence            0.001905 -0.031806   0.028130   
HealthLiteracy                 0.047514  0.032218  -0.019020   
Diagnosis                     -0.016864  0.011746  -0.023132   

                               SocioeconomicStatus  EducationLevel       BMI  \
Age                                      -0.007782        0.005520  0.006928   
Gender                                   -0.000957        0.014952  0.020455   
Ethnicity                                -0.017719        0.012042 -0.005440   
SocioeconomicStatus                       1.000000       -0.017693  0.016979   
EducationLevel                           -0.017693        1.000000 -0.001963   
BMI                                       0.016979       -0.001963  1.000000   
Smoking                                   0.025103        0.028154  0.025793   
AlcoholConsumption                        0.012669        0.011762 -0.006644   
PhysicalActivity                         -0.009270       -0.030274 -0.003442   
DietQuality                               0.009887       -0.022786  0.006032   
SleepQuality                              0.029760        0.004336  0.002152   
FamilyHistoryDiabetes                     0.035238       -0.020157  0.000993   
GestationalDiabetes                      -0.010478       -0.035680  0.002703   
PolycysticOvarySyndrome            

In [7]:
df.drop(['EducationLevel',
        'AlcoholConsumption',
        'PhysicalActivity', 
        'SleepQuality',
        'SlowHealingSores',
        'OccupationalExposureChemicals',
        'MedicalCheckupsFrequency'], inplace=True, axis=1)

In [8]:
from sklearn.model_selection import train_test_split
X = df.drop(["Diagnosis"],axis =1)
y = df["Diagnosis"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [9]:
def apply_models(X, y):
    # Split the data into training and test sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Initialize the StandardScaler
    scaler = StandardScaler()

    # Fit the scaler on the training data and transform both training and test data
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    # Define the models
    models = {
        'LogisticRegression': LogisticRegression(),
        'SVC': SVC(),
        'DecisionTree': DecisionTreeClassifier(),
        'RandomForest': RandomForestClassifier(),
        'ExtraTrees': ExtraTreesClassifier(),
        'AdaBoost': AdaBoostClassifier(),
        'GradientBoost': GradientBoostingClassifier(),
        'XGBoost': XGBClassifier(use_label_encoder=False, eval_metric='logloss'),
        'LightGBM': LGBMClassifier(),
        'CatBoost': CatBoostClassifier()
    }

    # Apply each model
    for model_name, model in models.items():
        print(f"\nClassification with {model_name}:\n{'-' * 30}")
        
        # Fit the model to the training data
        model.fit(X_train, y_train)

        # Make predictions on the test data
        y_pred = model.predict(X_test)

        # Print the accuracy score
        print("**Accuracy**:\n", accuracy_score(y_test, y_pred))

        # Print the confusion matrix
        print("\n**Confusion Matrix**:\n", confusion_matrix(y_test, y_pred))

        # Print the classification report
        print("\n**Classification Report**:\n", classification_report(y_test, y_pred))
apply_models(X, y)


Classification with LogisticRegression:
------------------------------
**Accuracy**:
 0.8297872340425532

**Confusion Matrix**:
 [[204  29]
 [ 35 108]]

**Classification Report**:
               precision    recall  f1-score   support

           0       0.85      0.88      0.86       233
           1       0.79      0.76      0.77       143

    accuracy                           0.83       376
   macro avg       0.82      0.82      0.82       376
weighted avg       0.83      0.83      0.83       376


Classification with SVC:
------------------------------
**Accuracy**:
 0.8563829787234043

**Confusion Matrix**:
 [[209  24]
 [ 30 113]]

**Classification Report**:
               precision    recall  f1-score   support

           0       0.87      0.90      0.89       233
           1       0.82      0.79      0.81       143

    accuracy                           0.86       376
   macro avg       0.85      0.84      0.85       376
weighted avg       0.86      0.86      0.86       37

C:\Users\austi\AppData\Roaming\Python\Python310\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


**Accuracy**:
 0.925531914893617

**Confusion Matrix**:
 [[223  10]
 [ 18 125]]

**Classification Report**:
               precision    recall  f1-score   support

           0       0.93      0.96      0.94       233
           1       0.93      0.87      0.90       143

    accuracy                           0.93       376
   macro avg       0.93      0.92      0.92       376
weighted avg       0.93      0.93      0.93       376


Classification with GradientBoost:
------------------------------
**Accuracy**:
 0.925531914893617

**Confusion Matrix**:
 [[226   7]
 [ 21 122]]

**Classification Report**:
               precision    recall  f1-score   support

           0       0.91      0.97      0.94       233
           1       0.95      0.85      0.90       143

    accuracy                           0.93       376
   macro avg       0.93      0.91      0.92       376
weighted avg       0.93      0.93      0.92       376


Classification with XGBoost:
------------------------------


C:\Users\austi\AppData\Roaming\Python\Python310\site-packages\xgboost\core.py:158: UserWarning: [05:02:38] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


**Accuracy**:
 0.9335106382978723

**Confusion Matrix**:
 [[226   7]
 [ 18 125]]

**Classification Report**:
               precision    recall  f1-score   support

           0       0.93      0.97      0.95       233
           1       0.95      0.87      0.91       143

    accuracy                           0.93       376
   macro avg       0.94      0.92      0.93       376
weighted avg       0.93      0.93      0.93       376


Classification with LightGBM:
------------------------------
[LightGBM] [Info] Number of positive: 609, number of negative: 894
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000443 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 3854
[LightGBM] [Info] Number of data points in the train set: 1503, number of used features: 36
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.405190 -> initscore=-0.383888
[LightGBM] [Info] Start training from score -0.383888
**Accuracy**