In [1]:
from sklearn.preprocessing import  OneHotEncoder
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, AdaBoostClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.svm import SVC
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from xgboost import XGBClassifier



In [2]:


numerical_features = [ 
    'Age', 
    'BMI', 
    'AlcoholConsumption', 
    'PhysicalActivity', 
    'DietQuality', 
    'SleepQuality', 
    'SystolicBP', 
    'DiastolicBP', 
    'FastingBloodSugar', 
    'HbA1c', 
    'SerumCreatinine', 
    'BUNLevels', 
    'CholesterolTotal', 
    'CholesterolLDL', 
    'CholesterolHDL', 
    'CholesterolTriglycerides', 
    'FatigueLevels', 
    'QualityOfLifeScore', 
    'MedicalCheckupsFrequency', 
    'MedicationAdherence', 
    'HealthLiteracy',
    'Diagnosis'
]

categorical_features = [
    'Gender', 
    'Ethnicity', 
    'SocioeconomicStatus', 
    'EducationLevel', 
    'Smoking', 
    'FamilyHistoryDiabetes', 
    'GestationalDiabetes', 
    'PolycysticOvarySyndrome', 
    'PreviousPreDiabetes', 
    'Hypertension', 
    'AntihypertensiveMedications', 
    'Statins', 
    'AntidiabeticMedications', 
    'FrequentUrination', 
    'ExcessiveThirst', 
    'UnexplainedWeightLoss', 
    'BlurredVision', 
    'SlowHealingSores', 
    'TinglingHandsFeet', 
    'HeavyMetalsExposure', 
    'OccupationalExposureChemicals', 
    'WaterQuality', 
    'Diagnosis'
]

In [3]:
df = pd.read_csv('diabetes_data.csv')
df = df.drop(['PatientID', 'DoctorInCharge'], axis=1)
df = df.round(2)
df.columns

Index(['Age', 'Gender', 'Ethnicity', 'SocioeconomicStatus', 'EducationLevel',
       'BMI', 'Smoking', 'AlcoholConsumption', 'PhysicalActivity',
       'DietQuality', 'SleepQuality', 'FamilyHistoryDiabetes',
       'GestationalDiabetes', 'PolycysticOvarySyndrome', 'PreviousPreDiabetes',
       'Hypertension', 'SystolicBP', 'DiastolicBP', 'FastingBloodSugar',
       'HbA1c', 'SerumCreatinine', 'BUNLevels', 'CholesterolTotal',
       'CholesterolLDL', 'CholesterolHDL', 'CholesterolTriglycerides',
       'AntihypertensiveMedications', 'Statins', 'AntidiabeticMedications',
       'FrequentUrination', 'ExcessiveThirst', 'UnexplainedWeightLoss',
       'FatigueLevels', 'BlurredVision', 'SlowHealingSores',
       'TinglingHandsFeet', 'QualityOfLifeScore', 'HeavyMetalsExposure',
       'OccupationalExposureChemicals', 'WaterQuality',
       'MedicalCheckupsFrequency', 'MedicationAdherence', 'HealthLiteracy',
       'Diagnosis'],
      dtype='object')

In [4]:
df_categorical = pd.read_csv('diabetes_data.csv', usecols=categorical_features)
df_categorical = df_categorical.round(4)
df_categorical.to_csv('categorical_features.csv', index=False)

In [5]:
df_numerical = pd.read_csv('diabetes_data.csv', usecols=numerical_features)
df_numerical = df_numerical.round(4)
df_numerical.to_csv('numerical_features.csv', index=False)

In [6]:
# Compute the correlation matrix
corr_c = df_categorical.corr()

corr_table = pd.DataFrame(corr_c)

corr_table

target_feature = 'Diagnosis'
corr_table


Gender  Ethnicity  SocioeconomicStatus  \
Gender                         1.000000  -0.010411            -0.000957   
Ethnicity                     -0.010411   1.000000            -0.017719   
SocioeconomicStatus           -0.000957  -0.017719             1.000000   
EducationLevel                 0.014952   0.012042            -0.017693   
Smoking                        0.000275  -0.022346             0.025103   
FamilyHistoryDiabetes          0.014000  -0.036448             0.035238   
GestationalDiabetes            0.024323   0.002852            -0.010478   
PolycysticOvarySyndrome        0.005413   0.025868             0.002258   
PreviousPreDiabetes            0.000338  -0.011837             0.046889   
Hypertension                  -0.010043   0.051279             0.017964   
AntihypertensiveMedications   -0.004204   0.001325            -0.013421   
Statins                       -0.015205  -0.045146            -0.008426   
AntidiabeticMedications        0.002473  -0.011613             0.003377   
FrequentUrination             -0.055795  -0.018348            -0.043773   
ExcessiveThirst                0.035167   0.015025             0.003345   
UnexplainedWeightLoss          0.001964  -0.005983            -0.025294   
BlurredVision                 -0.022708  -0.026439             0.008128   
SlowHealingSores               0.006712  -0.019843             0.003532   
TinglingHandsFeet              0.000386  -0.003145            -0.009587   
HeavyMetalsExposure           -0.042018  -0.025280            -0.022591   
OccupationalExposureChemicals -0.040498  -0.034420            -0.014755   
WaterQuality                   0.003230  -0.016378            -0.005197   
Diagnosis                      0.011746  -0.023132             0.025572   

                               EducationLevel   Smoking  \
Gender                               0.014952  0.000275   
Ethnicity                            0.012042 -0.022346   
SocioeconomicStatus                 -0.017693  0.025103   
EducationLevel                       1.000000  0.028154   
Smoking                              0.028154  1.000000   
FamilyHistoryDiabetes               -0.020157  0.044080   
GestationalDiabetes                 -0.035680  0.033020   
PolycysticOvarySyndrome              0.015293 -0.003715   
PreviousPreDiabetes                  0.024825 -0.014311   
Hypertension                         0.002668 -0.000267   
AntihypertensiveMedications         -0.061902 -0.018814   
Statins                             -0.010749  0.022468   
AntidiabeticMedications             -0.015742 -0.019120   
FrequentUrination                   -0.006709  0.004612   
ExcessiveThirst                      0.009365  0.038376   
UnexplainedWeightLoss                0.028747 -0.034071   
BlurredVision                       -0.035166  0.010503   
SlowHealingSores                     0.007986 -0.048083   
TinglingHandsFeet                   -0.030884 -0.037035   
HeavyMetalsExposure                 -0.001439  0.028792   
OccupationalExposureChemicals       -0.003291 -0.010179   
WaterQuality                         0.008046 -0.027000   
Diagnosis                           -0.002306  0.053829   

                               FamilyHistoryDiabetes  GestationalDiabetes  \
Gender                                      0.014000             0.024323   
Ethnicity                                  -0.036448             0.002852   
SocioeconomicStatus                         0.035238            -0.010478   
EducationLevel                             -0.020157            -0.035680   
Smoking                                     0.044080             0.033020   
FamilyHistoryDiabetes                       1.000000            -0.006614   
GestationalDiabetes                        -0.006614             1.000000   
PolycysticOvarySyndrome                     0.030051             0.014110   
PreviousPreDiabetes                        -0.013518             0.025814   
Hypertension                                0

In [7]:
# Compute the correlation matrix
corr_n = df_numerical.corr()

corr_table = pd.DataFrame(corr_n)

corr_table

target_feature = 'Diagnosis'
corr_table

Age       BMI  AlcoholConsumption  \
Age                       1.000000  0.006928           -0.017781   
BMI                       0.006928  1.000000           -0.006644   
AlcoholConsumption       -0.017781 -0.006644            1.000000   
PhysicalActivity          0.017811 -0.003442            0.018923   
DietQuality               0.036613  0.006032           -0.023770   
SleepQuality             -0.025744  0.002152           -0.003785   
SystolicBP               -0.003944 -0.012732            0.042797   
DiastolicBP               0.022890  0.002679            0.005671   
FastingBloodSugar        -0.022774 -0.007692           -0.023623   
HbA1c                     0.016533 -0.024381           -0.002629   
SerumCreatinine          -0.008761  0.007321           -0.037850   
BUNLevels                -0.011914  0.021573            0.006277   
CholesterolTotal          0.036122 -0.032015           -0.010661   
CholesterolLDL            0.005428  0.016210            0.013683   
CholesterolHDL            0.052419  0.017991           -0.036509   
CholesterolTriglycerides -0.026417 -0.037057           -0.014745   
FatigueLevels             0.018845 -0.030339            0.012270   
QualityOfLifeScore       -0.001543 -0.046976            0.011082   
MedicalCheckupsFrequency -0.003905 -0.021302            0.023039   
MedicationAdherence       0.001905 -0.009708            0.015339   
HealthLiteracy            0.047514  0.025464           -0.009071   
Diagnosis                -0.016864  0.014586           -0.009671   

                          PhysicalActivity  DietQuality  SleepQuality  \
Age                               0.017811     0.036613     -0.025744   
BMI                              -0.003442     0.006032      0.002152   
AlcoholConsumption                0.018923    -0.023770     -0.003785   
PhysicalActivity                  1.000000     0.001632      0.009425   
DietQuality                       0.001632     1.000000     -0.000137   
SleepQuality                      0.009425    -0.000137      1.000000   
SystolicBP                       -0.003797     0.017749      0.045473   
DiastolicBP                       0.010564     0.015764     -0.025270   
FastingBloodSugar                 0.024782    -0.004250      0.023836   
HbA1c                             0.013447    -0.013276      0.006244   
SerumCreatinine                  -0.016906    -0.022816      0.006356   
BUNLevels                         0.053740    -0.021180     -0.027454   
CholesterolTotal                  0.013745     0.028686     -0.010222   
CholesterolLDL                    0.005780    -0.008783     -0.014689   
CholesterolHDL                   -0.013839    -0.014351     -0.021224   
CholesterolTriglycerides         -0.034827     0.028419     -0.014646   
FatigueLevels                     0.004891     0.011270     -0.011559   
QualityOfLifeScore               -0.002443    -0.009517      0.021510   
MedicalCheckupsFrequency         -0.002935     0.029560      0.037652   
MedicationAdherence              -0.015420    -0.026133      0.024353   
HealthLiteracy                   -0.003800    -0.029877      0.002272   
Diagnosis                        -0.006412    -0.041432     -0.002937   

                          SystolicBP  DiastolicBP  FastingBloodSugar  \
Age                        -0.003944     0.022890          -0.022774   
BMI                        -0.012732     0.002679          -0.007692   
AlcoholConsumption          0.042797     0.005671          -0.023623   
PhysicalActivity           -0.003797     0.010564           0.024782   
DietQuality                 0.017749     0.015764          -0.004250   
SleepQuality                0.045473    -0.025270           0.023836   
SystolicBP                  1.000000     0.001470          -0.028172   
DiastolicBP                 0.001470     1.000000           0.031492   
FastingBloodSugar          -0.028172     0.031492           1.000000   
HbA1c                      -0.012792     0.030874           0.0028

In [8]:
# Compute the correlation matrix
corr = df.corr()

corr_table = pd.DataFrame(corr)

corr_table

target_feature = 'Diagnosis'
corr_table

Age    Gender  Ethnicity  \
Age                            1.000000 -0.000856  -0.049707   
Gender                        -0.000856  1.000000  -0.010411   
Ethnicity                     -0.049707 -0.010411   1.000000   
SocioeconomicStatus           -0.007782 -0.000957  -0.017719   
EducationLevel                 0.005520  0.014952   0.012042   
BMI                            0.006940  0.020461  -0.005436   
Smoking                        0.010858  0.000275  -0.022346   
AlcoholConsumption            -0.017778 -0.038466  -0.042906   
PhysicalActivity               0.017826  0.006670   0.002561   
DietQuality                    0.036593  0.002950  -0.000720   
SleepQuality                  -0.025763 -0.005764   0.002290   
FamilyHistoryDiabetes          0.018797  0.014000  -0.036448   
GestationalDiabetes            0.040820  0.024323   0.002852   
PolycysticOvarySyndrome       -0.001836  0.005413   0.025868   
PreviousPreDiabetes           -0.008952  0.000338  -0.011837   
Hypertension                  -0.032298 -0.010043   0.051279   
SystolicBP                    -0.003944 -0.035896  -0.014026   
DiastolicBP                    0.022890 -0.015992   0.035743   
FastingBloodSugar             -0.022770 -0.017247   0.020772   
HbA1c                          0.016537  0.042139  -0.038140   
SerumCreatinine               -0.008818 -0.020645  -0.013756   
BUNLevels                     -0.011912  0.004465   0.024923   
CholesterolTotal               0.036122 -0.004765   0.003048   
CholesterolLDL                 0.005427  0.038656   0.012341   
CholesterolHDL                 0.052415  0.015714  -0.000035   
CholesterolTriglycerides      -0.026417  0.007907   0.029323   
AntihypertensiveMedications   -0.024877 -0.004204   0.001325   
Statins                        0.013764 -0.015205  -0.045146   
AntidiabeticMedications        0.000084  0.002473  -0.011613   
FrequentUrination             -0.036307 -0.055795  -0.018348   
ExcessiveThirst               -0.011939  0.035167   0.015025   
UnexplainedWeightLoss         -0.041848  0.001964  -0.005983   
FatigueLevels                  0.018837  0.017518   0.002861   
BlurredVision                 -0.005455 -0.022708  -0.026439   
SlowHealingSores               0.008862  0.006712  -0.019843   
TinglingHandsFeet              0.011553  0.000386  -0.003145   
QualityOfLifeScore            -0.001539 -0.033461   0.018854   
HeavyMetalsExposure            0.007326 -0.042018  -0.025280   
OccupationalExposureChemicals  0.019327 -0.040498  -0.034420   
WaterQuality                  -0.039539  0.003230  -0.016378   
MedicalCheckupsFrequency      -0.003935  0.049876  -0.025747   
MedicationAdherence            0.001897 -0.031788   0.028174   
HealthLiteracy                 0.047515  0.032181  -0.018997   
Diagnosis                     -0.016864  0.011746  -0.023132   

                               SocioeconomicStatus  EducationLevel       BMI  \
Age                                      -0.007782        0.005520  0.006940   
Gender                                   -0.000957        0.014952  0.020461   
Ethnicity                                -0.017719        0.012042 -0.005436   
SocioeconomicStatus                       1.000000       -0.017693  0.016993   
EducationLevel                           -0.017693        1.000000 -0.001971   
BMI                                       0.016993       -0.001971  1.000000   
Smoking                                   0.025103        0.028154  0.025805   
AlcoholConsumption                        0.012676        0.011773 -0.006659   
PhysicalActivity                         -0.009241       -0.030256 -0.003420   
DietQuality                               0.009869       -0.022820  0.006038   
SleepQuality                              0.029706        0.004343  0.002119   
FamilyHistoryDiabetes                     0.035238       -0.020157  0.000992   
GestationalDiabetes                      -0.010478       -0.035680  0.002703   
PolycysticOvarySyndrome            

In [9]:
for col in df_categorical.columns:
    print(f"{col}: {df_categorical[col].nunique()}")

Gender: 2
Ethnicity: 4
SocioeconomicStatus: 3
EducationLevel: 4
Smoking: 2
FamilyHistoryDiabetes: 2
GestationalDiabetes: 2
PolycysticOvarySyndrome: 2
PreviousPreDiabetes: 2
Hypertension: 2
AntihypertensiveMedications: 2
Statins: 2
AntidiabeticMedications: 2
FrequentUrination: 2
ExcessiveThirst: 2
UnexplainedWeightLoss: 2
BlurredVision: 2
SlowHealingSores: 2
TinglingHandsFeet: 2
HeavyMetalsExposure: 2
OccupationalExposureChemicals: 2
WaterQuality: 2
Diagnosis: 2


In [10]:
for col in df_numerical.columns:
    print(f"{col}: {df_numerical[col].nunique()}")

Age: 71
BMI: 1875
AlcoholConsumption: 1866
PhysicalActivity: 1862
DietQuality: 1871
SleepQuality: 1850
SystolicBP: 90
DiastolicBP: 60
FastingBloodSugar: 1876
HbA1c: 1845
SerumCreatinine: 1845
BUNLevels: 1875
CholesterolTotal: 1879
CholesterolLDL: 1879
CholesterolHDL: 1877
CholesterolTriglycerides: 1877
FatigueLevels: 1865
QualityOfLifeScore: 1876
MedicalCheckupsFrequency: 1837
MedicationAdherence: 1860
HealthLiteracy: 1858
Diagnosis: 2


In [11]:
df.drop(['EducationLevel',
        'AlcoholConsumption',
        'PhysicalActivity', 
        'SleepQuality',
        'SlowHealingSores',
        'OccupationalExposureChemicals',
        'MedicalCheckupsFrequency',
        'HeavyMetalsExposure',
        'WaterQuality',
        ], inplace=True, axis=1)
df.to_csv('best_features.csv', index=False)

In [12]:
best_feat = pd.read_csv('best_features.csv')
best_feat


Age  Gender  Ethnicity  SocioeconomicStatus    BMI  Smoking  \
0      44       0          1                    2  32.99        1   
1      51       1          0                    1  39.92        0   
2      89       1          0                    1  19.78        0   
3      21       1          1                    1  32.38        1   
4      27       1          0                    1  16.81        0   
...   ...     ...        ...                  ...    ...      ...   
1874   37       0          0                    2  20.81        0   
1875   80       1          0                    2  27.69        0   
1876   38       1          0                    0  35.64        0   
1877   43       0          1                    2  32.42        0   
1878   85       1          0                    2  33.15        0   

      DietQuality  FamilyHistoryDiabetes  GestationalDiabetes  \
0            4.90                      1                    1   
1            8.94                      0                    0   
2            7.72                      1                    0   
3            4.80                      1                    1   
4            2.53                      0                    0   
...           ...                    ...                  ...   
1874         8.34                      0                    0   
1875         3.03                      1                    1   
1876         2.66                      0                    0   
1877         8.74                      1                    0   
1878         5.13                      1                    0   

      PolycysticOvarySyndrome  ...  FrequentUrination  ExcessiveThirst  \
0                           0  ...                  0                0   
1                           0  ...                  0                0   
2                           0  ...                  0                0   
3                           0  ...                  0                0   
4                           0  ...                  0                0   
...                       ...  ...                ...              ...   
1874                        0  ...                  0                1   
1875                        0  ...                  0                0   
1876                        0  ...                  0                0   
1877                        1  ...                  0                0   
1878                        0  ...                  1                0   

      UnexplainedWeightLoss  FatigueLevels  BlurredVision  TinglingHandsFeet  \
0                         0           9.53              0                  1   
1                         0           0.12              0                  0   
2                         0           9.64              0                  0   
3                         0           3.40              0                  0   
4                         0           2.92              0                  0   
...                     ...            ...            ...                ...   
1874                      0           3.69              1                  1   
1875                      0           4.23              0                  0   
1876                      0           1.17              0                  0   
1877                      0           9.73              0                  0   
1878                      0           4.36              0                  1   

      QualityOfLifeScore  MedicationAdherence  HealthLiteracy  Diagnosis  
0                  73.77                 4.49            7.21          1  
1                  91.45                 5.96            5.02          1  
2                  54.49                 8.95            7.03          0  
3                  77.87                 3.12            4.72          0  
4                  37.73                 6.98            7.89          0  
...                  ...                  ...             ...        ...  
1874               88

In [13]:
from sklearn.model_selection import train_test_split
X = df_numerical.drop(["Diagnosis"],axis =1)
y = df_numerical["Diagnosis"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)
def apply_models(X, y):
    # Split the data into training and test sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Initialize the StandardScaler
    scaler = StandardScaler()

    # Fit the scaler on the training data and transform both training and test data
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    # Define the models
    models = {
        'LogisticRegression': LogisticRegression(),
        'SVC': SVC(),
        'DecisionTree': DecisionTreeClassifier(),
        'RandomForest': RandomForestClassifier(),
        'ExtraTrees': ExtraTreesClassifier(),
        'AdaBoost': AdaBoostClassifier(),
        'GradientBoost': GradientBoostingClassifier(),
        'XGBoost': XGBClassifier(use_label_encoder=False, eval_metric='logloss'),
        'LightGBM': LGBMClassifier(),
        'CatBoost': CatBoostClassifier()
    }

    # Apply each model
    for model_name, model in models.items():
        print(f"\nClassification with {model_name}:\n{'-' * 30}")
        
        # Fit the model to the training data
        model.fit(X_train, y_train)

        # Make predictions on the test data
        y_pred = model.predict(X_test)

        # Print the accuracy score
        print("**Accuracy**:\n", accuracy_score(y_test, y_pred))

        # Print the confusion matrix
        print("\n**Confusion Matrix**:\n", confusion_matrix(y_test, y_pred))

        # Print the classification report
        print("\n**Classification Report**:\n", classification_report(y_test, y_pred))
apply_models(X, y)


Classification with LogisticRegression:
------------------------------
**Accuracy**:
 0.800531914893617

**Confusion Matrix**:
 [[202  31]
 [ 44  99]]

**Classification Report**:
               precision    recall  f1-score   support

           0       0.82      0.87      0.84       233
           1       0.76      0.69      0.73       143

    accuracy                           0.80       376
   macro avg       0.79      0.78      0.78       376
weighted avg       0.80      0.80      0.80       376


Classification with SVC:
------------------------------
**Accuracy**:
 0.8191489361702128

**Confusion Matrix**:
 [[210  23]
 [ 45  98]]

**Classification Report**:
               precision    recall  f1-score   support

           0       0.82      0.90      0.86       233
           1       0.81      0.69      0.74       143

    accuracy                           0.82       376
   macro avg       0.82      0.79      0.80       376
weighted avg       0.82      0.82      0.82       376

c:\Users\lucas\anaconda3\envs\activities\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


**Accuracy**:
 0.8882978723404256

**Confusion Matrix**:
 [[220  13]
 [ 29 114]]

**Classification Report**:
               precision    recall  f1-score   support

           0       0.88      0.94      0.91       233
           1       0.90      0.80      0.84       143

    accuracy                           0.89       376
   macro avg       0.89      0.87      0.88       376
weighted avg       0.89      0.89      0.89       376


Classification with GradientBoost:
------------------------------
**Accuracy**:
 0.901595744680851

**Confusion Matrix**:
 [[227   6]
 [ 31 112]]

**Classification Report**:
               precision    recall  f1-score   support

           0       0.88      0.97      0.92       233
           1       0.95      0.78      0.86       143

    accuracy                           0.90       376
   macro avg       0.91      0.88      0.89       376
weighted avg       0.91      0.90      0.90       376


Classification with XGBoost:
------------------------------

c:\Users\lucas\anaconda3\envs\activities\Lib\site-packages\xgboost\core.py:158: UserWarning: [20:09:17] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[LightGBM] [Info] Number of positive: 609, number of negative: 894
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000680 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4814
[LightGBM] [Info] Number of data points in the train set: 1503, number of used features: 21
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.405190 -> initscore=-0.383888
[LightGBM] [Info] Start training from score -0.383888
**Accuracy**:
 0.898936170212766

**Confusion Matrix**:
 [[225   8]
 [ 30 113]]

**Classification Report**:
               precision    recall  f1-score   support

           0       0.88      0.97      0.92       233
           1       0.93      0.79      0.86       143

    accuracy                           0.90       376
   macro avg       0.91      0.88      0.89       376
weighted avg       0.90      0.90      0.90       376


Classifica

In [14]:
from sklearn.model_selection import train_test_split
X = df_categorical.drop(["Diagnosis"],axis =1)
y = df_categorical["Diagnosis"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)
def apply_models(X, y):
    # Split the data into training and test sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Initialize the StandardScaler
    scaler = StandardScaler()

    # Fit the scaler on the training data and transform both training and test data
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    # Define the models
    models = {
        'LogisticRegression': LogisticRegression(),
        'SVC': SVC(),
        'DecisionTree': DecisionTreeClassifier(),
        'RandomForest': RandomForestClassifier(),
        'ExtraTrees': ExtraTreesClassifier(),
        'AdaBoost': AdaBoostClassifier(),
        'GradientBoost': GradientBoostingClassifier(),
        'XGBoost': XGBClassifier(use_label_encoder=False, eval_metric='logloss'),
        'LightGBM': LGBMClassifier(),
        'CatBoost': CatBoostClassifier()
    }

    # Apply each model
    for model_name, model in models.items():
        print(f"\nClassification with {model_name}:\n{'-' * 30}")
        
        # Fit the model to the training data
        model.fit(X_train, y_train)

        # Make predictions on the test data
        y_pred = model.predict(X_test)

        # Print the accuracy score
        print("**Accuracy**:\n", accuracy_score(y_test, y_pred))

        # Print the confusion matrix
        print("\n**Confusion Matrix**:\n", confusion_matrix(y_test, y_pred))

        # Print the classification report
        print("\n**Classification Report**:\n", classification_report(y_test, y_pred))
apply_models(X, y)


Classification with LogisticRegression:
------------------------------
**Accuracy**:
 0.625

**Confusion Matrix**:
 [[194  39]
 [102  41]]

**Classification Report**:
               precision    recall  f1-score   support

           0       0.66      0.83      0.73       233
           1       0.51      0.29      0.37       143

    accuracy                           0.62       376
   macro avg       0.58      0.56      0.55       376
weighted avg       0.60      0.62      0.59       376


Classification with SVC:
------------------------------
**Accuracy**:
 0.6382978723404256

**Confusion Matrix**:
 [[200  33]
 [103  40]]

**Classification Report**:
               precision    recall  f1-score   support

           0       0.66      0.86      0.75       233
           1       0.55      0.28      0.37       143

    accuracy                           0.64       376
   macro avg       0.60      0.57      0.56       376
weighted avg       0.62      0.64      0.60       376


Classific

c:\Users\lucas\anaconda3\envs\activities\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


**Accuracy**:
 0.6303191489361702

**Confusion Matrix**:
 [[194  39]
 [100  43]]

**Classification Report**:
               precision    recall  f1-score   support

           0       0.66      0.83      0.74       233
           1       0.52      0.30      0.38       143

    accuracy                           0.63       376
   macro avg       0.59      0.57      0.56       376
weighted avg       0.61      0.63      0.60       376


Classification with XGBoost:
------------------------------
**Accuracy**:
 0.6037234042553191

**Confusion Matrix**:
 [[170  63]
 [ 86  57]]

**Classification Report**:
               precision    recall  f1-score   support

           0       0.66      0.73      0.70       233
           1       0.47      0.40      0.43       143

    accuracy                           0.60       376
   macro avg       0.57      0.56      0.56       376
weighted avg       0.59      0.60      0.60       376


Classification with LightGBM:
------------------------------
[Li

c:\Users\lucas\anaconda3\envs\activities\Lib\site-packages\xgboost\core.py:158: UserWarning: [20:09:27] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


**Accuracy**:
 0.625

**Confusion Matrix**:
 [[175  58]
 [ 83  60]]

**Classification Report**:
               precision    recall  f1-score   support

           0       0.68      0.75      0.71       233
           1       0.51      0.42      0.46       143

    accuracy                           0.62       376
   macro avg       0.59      0.59      0.59       376
weighted avg       0.61      0.62      0.62       376


Classification with CatBoost:
------------------------------
Learning rate set to 0.01226
0:	learn: 0.6922217	total: 16.6ms	remaining: 16.6s
1:	learn: 0.6911021	total: 20.5ms	remaining: 10.3s
2:	learn: 0.6899316	total: 23.7ms	remaining: 7.87s
3:	learn: 0.6885403	total: 27.8ms	remaining: 6.91s
4:	learn: 0.6875951	total: 30.7ms	remaining: 6.1s
5:	learn: 0.6864470	total: 33.4ms	remaining: 5.53s
6:	learn: 0.6847350	total: 36.7ms	remaining: 5.21s
7:	learn: 0.6834138	total: 40ms	remaining: 4.96s
8:	learn: 0.6821820	total: 43.3ms	remaining: 4.76s
9:	learn: 0.6812116	total: 46

In [15]:
from sklearn.model_selection import train_test_split
X = df.drop(["Diagnosis"],axis =1)
y = df["Diagnosis"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)
def apply_models(X, y):
    # Split the data into training and test sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Initialize the StandardScaler
    scaler = StandardScaler()

    # Fit the scaler on the training data and transform both training and test data
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    # Define the models
    models = {
        'LogisticRegression': LogisticRegression(),
        'SVC': SVC(),
        'DecisionTree': DecisionTreeClassifier(),
        'RandomForest': RandomForestClassifier(),
        'ExtraTrees': ExtraTreesClassifier(),
        'AdaBoost': AdaBoostClassifier(),
        'GradientBoost': GradientBoostingClassifier(),
        'XGBoost': XGBClassifier(use_label_encoder=False, eval_metric='logloss'),
        'LightGBM': LGBMClassifier(),
        'CatBoost': CatBoostClassifier()
    }

    # Apply each model
    for model_name, model in models.items():
        print(f"\nClassification with {model_name}:\n{'-' * 30}")
        
        # Fit the model to the training data
        model.fit(X_train, y_train)

        # Make predictions on the test data
        y_pred = model.predict(X_test)

        # Print the accuracy score
        print("**Accuracy**:\n", accuracy_score(y_test, y_pred))

        # Print the confusion matrix
        print("\n**Confusion Matrix**:\n", confusion_matrix(y_test, y_pred))

        # Print the classification report
        print("\n**Classification Report**:\n", classification_report(y_test, y_pred))
apply_models(X, y)


Classification with LogisticRegression:
------------------------------
**Accuracy**:
 0.8430851063829787

**Confusion Matrix**:
 [[207  26]
 [ 33 110]]

**Classification Report**:
               precision    recall  f1-score   support

           0       0.86      0.89      0.88       233
           1       0.81      0.77      0.79       143

    accuracy                           0.84       376
   macro avg       0.84      0.83      0.83       376
weighted avg       0.84      0.84      0.84       376


Classification with SVC:
------------------------------
**Accuracy**:
 0.848404255319149

**Confusion Matrix**:
 [[209  24]
 [ 33 110]]

**Classification Report**:
               precision    recall  f1-score   support

           0       0.86      0.90      0.88       233
           1       0.82      0.77      0.79       143

    accuracy                           0.85       376
   macro avg       0.84      0.83      0.84       376
weighted avg       0.85      0.85      0.85       376

c:\Users\lucas\anaconda3\envs\activities\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


**Accuracy**:
 0.925531914893617

**Confusion Matrix**:
 [[221  12]
 [ 16 127]]

**Classification Report**:
               precision    recall  f1-score   support

           0       0.93      0.95      0.94       233
           1       0.91      0.89      0.90       143

    accuracy                           0.93       376
   macro avg       0.92      0.92      0.92       376
weighted avg       0.93      0.93      0.93       376


Classification with GradientBoost:
------------------------------
**Accuracy**:
 0.925531914893617

**Confusion Matrix**:
 [[226   7]
 [ 21 122]]

**Classification Report**:
               precision    recall  f1-score   support

           0       0.91      0.97      0.94       233
           1       0.95      0.85      0.90       143

    accuracy                           0.93       376
   macro avg       0.93      0.91      0.92       376
weighted avg       0.93      0.93      0.92       376


Classification with XGBoost:
------------------------------


c:\Users\lucas\anaconda3\envs\activities\Lib\site-packages\xgboost\core.py:158: UserWarning: [20:09:33] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


**Accuracy**:
 0.9228723404255319

**Confusion Matrix**:
 [[226   7]
 [ 22 121]]

**Classification Report**:
               precision    recall  f1-score   support

           0       0.91      0.97      0.94       233
           1       0.95      0.85      0.89       143

    accuracy                           0.92       376
   macro avg       0.93      0.91      0.92       376
weighted avg       0.92      0.92      0.92       376


Classification with CatBoost:
------------------------------
Learning rate set to 0.01226
0:	learn: 0.6809763	total: 6.78ms	remaining: 6.78s
1:	learn: 0.6684720	total: 12.2ms	remaining: 6.08s
2:	learn: 0.6576420	total: 17.7ms	remaining: 5.89s
3:	learn: 0.6456288	total: 22.6ms	remaining: 5.62s
4:	learn: 0.6354516	total: 27.2ms	remaining: 5.41s
5:	learn: 0.6255075	total: 32.5ms	remaining: 5.38s
6:	learn: 0.6145230	total: 38.1ms	remaining: 5.4s
7:	learn: 0.6046610	total: 42.9ms	remaining: 5.32s
8:	learn: 0.5940413	total: 49.4ms	remaining: 5.44s
9:	learn: 0.58

In [16]:
###All features
X = df.drop('Diagnosis', axis=1)
y = df['Diagnosis']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = CatBoostClassifier()

# Fit the model to the training data
model.fit(X_train, y_train)

        # Make predictions on the test data
y_pred = model.predict(X_test)

from joblib import dump, load
dump(model, 'diabetes.joblib')

def diabetes(Age, Gender, Ethnicity, SocioeconomicStatus,
       BMI, Smoking,
       DietQuality, FamilyHistoryDiabetes,
       GestationalDiabetes, PolycysticOvarySyndrome, PreviousPreDiabetes,
       Hypertension, SystolicBP, DiastolicBP, FastingBloodSugar,
       HbA1c, SerumCreatinine, BUNLevels, CholesterolTotal,
       CholesterolLDL, CholesterolHDL, CholesterolTriglycerides,
       AntihypertensiveMedications, Statins, AntidiabeticMedications,
       FrequentUrination, ExcessiveThirst, UnexplainedWeightLoss,
       FatigueLevels, BlurredVision,
       TinglingHandsFeet, QualityOfLifeScore, HeavyMetalsExposure, WaterQuality,
       MedicationAdherence, HealthLiteracy):
#turning the arguments into a numpy array  

       x = np.array([Age, Gender, Ethnicity, SocioeconomicStatus,
       BMI, Smoking,
       DietQuality, FamilyHistoryDiabetes,
       GestationalDiabetes, PolycysticOvarySyndrome, PreviousPreDiabetes,
       Hypertension, SystolicBP, DiastolicBP, FastingBloodSugar,
       HbA1c, SerumCreatinine, BUNLevels, CholesterolTotal,
       CholesterolLDL, CholesterolHDL, CholesterolTriglycerides,
       AntihypertensiveMedications, Statins, AntidiabeticMedications,
       FrequentUrination, ExcessiveThirst, UnexplainedWeightLoss,
       FatigueLevels, BlurredVision,
       TinglingHandsFeet, QualityOfLifeScore, HeavyMetalsExposure, WaterQuality,
       MedicationAdherence, HealthLiteracy])
       prediction = model.predict(x.reshape(1, -1))

       return prediction



Learning rate set to 0.01226
0:	learn: 0.6809763	total: 7.88ms	remaining: 7.88s
1:	learn: 0.6684720	total: 13.5ms	remaining: 6.75s
2:	learn: 0.6576420	total: 19.4ms	remaining: 6.46s
3:	learn: 0.6456288	total: 24.3ms	remaining: 6.06s
4:	learn: 0.6354516	total: 29.3ms	remaining: 5.83s
5:	learn: 0.6255075	total: 34.5ms	remaining: 5.71s
6:	learn: 0.6145230	total: 39.2ms	remaining: 5.57s
7:	learn: 0.6046610	total: 46.6ms	remaining: 5.77s
8:	learn: 0.5940413	total: 53.1ms	remaining: 5.84s
9:	learn: 0.5828725	total: 58.6ms	remaining: 5.8s
10:	learn: 0.5718134	total: 63.4ms	remaining: 5.7s
11:	learn: 0.5619884	total: 69.3ms	remaining: 5.7s
12:	learn: 0.5536430	total: 73.8ms	remaining: 5.6s
13:	learn: 0.5431617	total: 77.9ms	remaining: 5.49s
14:	learn: 0.5340693	total: 83.9ms	remaining: 5.51s
15:	learn: 0.5256729	total: 88.7ms	remaining: 5.46s
16:	learn: 0.5179114	total: 93.9ms	remaining: 5.43s
17:	learn: 0.5094004	total: 98.5ms	remaining: 5.37s
18:	learn: 0.5018995	total: 105ms	remaining: 5.42

In [20]:
# import gradio as gr
# outputs= gr.Textbox(label= 'Diagnosis')

# app = gr.Interface(fn=diabetes, inputs=['number','number','number','number','number','number','number','number','number','number','number','number','number','number','number','number','number','number','number','number','number','number','number','number','number','number','number','number','number','number','number','number','number','number','number','number'], outputs=outputs,description="This is a diabetes model")


In [19]:
import gradio as gr
choices = [("Male", 0), ("Female", 1)]
iface = gr.Interface(
    fn=diabetes,
    inputs=[
        gr.Textbox(label="Input your age"),

        gr.Radio(label="Gender", choices=choices),
        gr.Textbox(label="Input your Ethnicity"),
        gr.Textbox(label="Input your Socio economic"),
        gr.Textbox(label="Input your BMI"),
        gr.Textbox(label="Input your smoking"),
        gr.Textbox(label="Input your diet"),

        gr.Textbox(label="Input your history"),
        gr.Textbox(label="Input your gest"),
        gr.Textbox(label="Input your poly"),
        gr.Textbox(label="Input your prev"),

        gr.Textbox(label="Input your hyper"),
        gr.Textbox(label="Input your sys"),
        gr.Textbox(label="Input your dia"),
        gr.Textbox(label="Input your fasting"),
        gr.Textbox(label="Input your a1c"),
        gr.Textbox(label="Input your creatine"),
        gr.Textbox(label="Input your bun"),
        gr.Textbox(label="Input your cholest"),
        gr.Textbox(label="Input your ldl"),
        gr.Textbox(label="Input your hdl"),
        gr.Textbox(label="Input your tri"),
        gr.Textbox(label="Input your ahmed"),
        gr.Textbox(label="Input your statins"),
        gr.Textbox(label="Input your adm"),
        gr.Textbox(label="Input your pee"),
        gr.Textbox(label="Input your thirst"),
        gr.Textbox(label="Input your weight"),
        gr.Textbox(label="Input your fatigue"),
        gr.Textbox(label="Input your vision"),
        gr.Textbox(label="Input your tingles"),
        gr.Textbox(label="Input your qol"),
        gr.Textbox(label="Input your med adh"),
        gr.Textbox(label="Input your Health lit"),
       
    ],
    outputs="text",  # Adjust output type if needed
)

ModuleNotFoundError: No module named 'gradio'

In [67]:
iface.launch(share=True)

Running on local URL:  http://127.0.0.1:7862
Running on public URL: https://951935473f48010cf3.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)


C:\Users\austi\AppData\Roaming\Python\Python310\site-packages\gradio\helpers.py:978: UserWarning: Unexpected argument. Filling with None.
  warnings.warn("Unexpected argument. Filling with None.")
